{{- if .Values.tunnel.enabled }}
apiVersion: networking.cfargotunnel.com/v1alpha1
kind: TunnelBinding
metadata:
  name: {{ .Values.name }}-binding
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
    app.kubernetes.io/name: grafana
    app.kubernetes.io/instance: {{ .Values.name }}
    app.kubernetes.io/managed-by: dockify
subjects:
  - kind: Service
    name: {{ .Values.name }}-service
    spec:
      fqdn: {{ .Values.tunnel.fqdn }}
      noTlsVerify: false
      target: http://{{ .Values.name }}-service.{{ .Values.namespace }}.svc.cluster.local:3000
tunnelRef:
  kind: ClusterTunnel
  name: {{ .Values.tunnel.clusterTunnel }}
{{- end }}
