apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cluster.yaml
  - secret.yaml
  - ingressroute-tcp.yaml
  - ingressroute-tcp-ro.yaml
  - ingressroute-tcp-r.yaml
  - pooler.yaml
  - pooler-ro.yaml
  - pooler-r.yaml
  - pooler-ingressroute-tcp.yaml
  - pooler-ingressroute-tcp-ro.yaml
  - pooler-ingressroute-tcp-r.yaml

images:
  - name: postgres
    newName: ghcr.io/cloudnative-pg/postgresql
    newTag: "16"
